### ISSUE TITLE
Errors with `thiserror`

### ISSUE THREAD

**Issue by AleCandido** [AleCandido/quad#11]
@AlexRaiteri you already nicely organized your errors with an `enum`:

https://github.com/AleCandido/quad/blob/1bef7203c6f0f39132b019d1f0cb40256beeab24/src/result_state.rs#L1-L28

But you didn't make it an actual [`Error` trait](https://doc.rust-lang.org/std/error/trait.Error.html) implementor, and because of this you needed a custom solution to `unwrap`:
https://github.com/AleCandido/quad/blob/1bef7203c6f0f39132b019d1f0cb40256beeab24/src/qag_integrator_result.rs#L38-L49

However, with possibly less code (but very similar to yours) and a popular lib, i.e. [`thiserror`](https://github.com/dtolnay/thiserror) we can turn your result into an actual `Result`.

**Comment by AleCandido** [comment]
@AlexRaiteri this I can do by myself, but I wrote here to remember, since I will only do it after merging #6 and #10

**Comment by AlexRaiteri** [comment]
I Tried to solve this in #25 .
