### ISSUE TITLE
Optional points

### ISSUE THREAD

**Issue by AlexRaiteri** [AleCandido/quad#13]
The optional list of point must be sorted and point outside the interval must be removed. ( introduce a constructor? )

**Comment by AleCandido** [comment]
Part of the clean-up. We could consider two options:
- sorting ourselves, or
- raising an error if not sorted

**Comment by AlexRaiteri** [comment]
I solved it by sorting them inside the method.
There remains the problem of how to transform the points in the semi-infinite / infinite case, this issue is related to #18.
