### ISSUE TITLE
Python benchmarks

### ISSUE THREAD

**Issue by AleCandido** [AleCandido/quad#16]
In #10 I added the basic testing infrastructure with Pytest.

However, Pytest is the most suited for performance benchmarks, and as mentioned in #5 it would be better to set up [`asv`](https://asv.readthedocs.io/en/stable/).

Even the corresponding workflow will have to be adjusted.

**Comment by AlexRaiteri** [comment]
I have started to do the setup of asv, now we should decide whether to save the results on a website (or gh-pages branche).
