### ISSUE TITLE
Use `ndarray`

### ISSUE THREAD

**Issue by AleCandido** [AleCandido/quad#21]
In principle, they should be equivalent to what you're already doing, but they have some built-in abstractions that might be useful to save some implementation:

E.g.
https://github.com/AleCandido/quad/blob/e8dc5e9b2012ea8dea949be84b7679b6268fa14e/quad/src/qag_par.rs#L414-L424
are already implemented in `ndarray`.
https://docs.rs/ndarray/0.15.6/ndarray/struct.ArrayBase.html#arithmetic-operations

**Comment by AlexRaiteri** [comment]
ndarray does not need generics to work?

**Comment by AleCandido** [comment]
Same as `Vec<T>` and `[T]`.

**Comment by AlexRaiteri** [comment]
Done it in #31 .
