### ISSUE TITLE
Unify `qag` and `qag_par`

### ISSUE THREAD

**Issue by AleCandido** [AleCandido/quad#26]
It would be ideal if `qag` were implemented as the limit of `qag_par` when the number of threads is just set to 1.

The moment the performances of the two are confirmed to be the same (possibly with as few as possible explicit `if` branches for the `threads_num == 1` case), then I would:
- drop the current `qag`
- rename `qag_par` to `qag`

**Comment by AlexRaiteri** [comment]
Isn't Qag necessary for quad-py?

**Comment by AleCandido** [comment]
I believe that at some point you said that you managed to make Python working with the parallel one.

However, in case that has been a misunderstanding, I believe we can still share most of the implementation.
But at the moment this is not necessarily the most urgent priority, so keep going with the benchmarks and other features (the most urgent one is to prove extensively that `quad` can reproduce SciPy results, and beat performances in the $\mathbb{R} \to \mathbb{R}^N$ case).

**Comment by AlexRaiteri** [comment]
I didn't think about using qag_par in quad-py because is useless for number_of_thread != 1, but fixing number_of_thread = 1 can be used.
I added it in #25 to test the performance vs qag.

**Comment by AleCandido** [comment]
> I didn't think about using qag_par in quad-py because is useless for number_of_thread != 1, but fixing number_of_thread = 1 can be used.

The advantage is not about performances (for `number_of_threads = 1` it should be the same, or slightly worse, that is acceptable if very mild), but rather not maintaining two separate pieces of code :)

**Comment by AlexRaiteri** [comment]
Done it.
The bench is in #28 ( workflow ) and have been unified in #30.
